version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  python_unit_test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Set Up Python Environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Unit Tests with Coverage
          command: |
            . venv/bin/activate
            coverage run -m unittest discover -s tests
            coverage xml
      - persist_to_workspace:
          root: .
          paths:
            - coverage.xml
      - run:
          name: List Files in Workspace
          command: ls -la /home/circleci/project

  sonarcloud_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - run:
          name: Check Coverage File in Workspace
          command: ls -la /workspace
      - run:
          name: Run SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORG_KEY \
              -Dsonar.sources=. \
              -Dsonar.exclusions=**/build-wrapper-dump.json,**/Dockerfile \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.token=$SONAR_TOKEN \
              -Dsonar.python.coverage.reportPaths=/workspace/coverage.xml \
              -Dsonar.python.version=3.8

  docker_build_and_push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t $DOCKERHUB_USERNAME/todo_app:$version .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_ACCESS_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            docker push $DOCKERHUB_USERNAME/todo_app:$version

workflows:
  version: 2
  build_and_test:
    jobs:
      - python_unit_test
      - sonarcloud_scan:
          requires:
            - python_unit_test
      # - docker_build_and_push:
      #     requires:
      #       - sonarcloud_scan
