version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Set Up Python Environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests with Coverage
          command: |
            . venv/bin/activate
            coverage run -m unittest discover -s tests
            coverage xml
      - store_artifacts: # this step will be removed later, it is added just to see coverage data
          path: coverage.xml
          destination: coverage_reports

workflows:
  version: 2
  test:
    jobs:
      - test