version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/project

  sonar-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    working_directory: ~/project

jobs:
  python_unit_test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Set Up Python Environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            coverage run -m unittest discover -s tests
      - run:
          name: Generate Coverage Report
          command: |
            . venv/bin/activate
            coverage xml
      - run:
          name: pwd
          command: pwd
      - run:
          name: list
          command: ls -lrth

  sonarcloud_scan:
    executor: sonar-executor
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd
      - run:
          name: list
          command: ls -lrth

workflows:
  version: 2
  build_and_test:
    jobs:
      - python_unit_test
      - sonarcloud_scan:
          requires:
            - python_unit_test